-- AlterTable
ALTER TABLE "Stream" ADD COLUMN     "createAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "play" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "playedTs" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
